import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import Sidebar from "@/components/layout/Sidebar";
import NavigationBar from "@/components/layout/NavigationBar";
import { Toaster } from "@/components/ui/sonner"


const fontSans = FontSans({
variable: "--font-sans",
subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children
    }: {
    children: React.ReactNode;
    }) 
{   
    return (
        <html lang="en">
            <body
                className={cn(
                "min-h-screen bg-background antialiased",
                fontSans.variable,
                "font-sans",
                )}
            >
                <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">

                <Sidebar className="sticky top-0 h-screen"/>
                <div className="flex flex-col">
                    <NavigationBar className="sticky top-0 z-50 w-full" />

                    <main className="flex-1 p-4 lg:p-6">
                    {children}
                    <Toaster richColors position="top-right" style={{ fontFamily: 'inherit' }}/>
                    </main>
                </div>
                
                </div>
            </body>
        </html>
    );
}
